export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ARTICLES_LOADING_SUCCEEDED = 'ARTICLES_LOADING_SUCCEEDED';
export const ARTICLES_LOADING_FAILED = 'ARTICLES_LOADING_FAILED';

export const ARTICLES_START_PARSING = 'ARTICLES_START_PARSING';
export const ARTICLES_PARSING_SUCCEEDED = 'ARTICLES_PARSING_SUCCEEDED';
export const ARTICLES_PARSING_FAILED = 'ARTICLES_PARSING_SUCCEEDED';

export const STATISTICS_LOADING = 'STATISTICS_LOADING';
export const STATISTICS_LOADING_SUCCEEDED = 'STATISTICS_LOADING_SUCCEEDED';
export const STATISTICS_LOADING_FAILED = 'STATISTICS_LOADING_FAILED';

export const START_SUBMIT = 'START_SUBMIT';
export const STOP_SUBMIT = 'STOP_SUBMIT';
export const SUBMIT_SUCCEDED = 'SUBMIT_SUCCEDED';

export const CATEGORIES = ["politics", "health", "sport"]
